# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vcf_parser_map <- function(vcf_file, out) {
    .Call(`_MVP_vcf_parser_map`, vcf_file, out)
}

vcf_parser_genotype <- function(vcf_file, pBigMat, pos) {
    invisible(.Call(`_MVP_vcf_parser_genotype`, vcf_file, pBigMat, pos))
}

hapmap_parser_map <- function(hmp_file, out) {
    .Call(`_MVP_hapmap_parser_map`, hmp_file, out)
}

hapmap_parser_genotype <- function(hmp_file, pBigMat) {
    invisible(.Call(`_MVP_hapmap_parser_genotype`, hmp_file, pBigMat))
}

numeric_scan <- function(num_file) {
    .Call(`_MVP_numeric_scan`, num_file)
}

write_bfile <- function(pBigMat, bed_file) {
    invisible(.Call(`_MVP_write_bfile`, pBigMat, bed_file))
}

read_bfile <- function(bed_file, pBigMat, maxLine) {
    invisible(.Call(`_MVP_read_bfile`, bed_file, pBigMat, maxLine))
}

