# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRow <- function(pBigMat, row) {
    .Call(`_rMVP_getRow`, pBigMat, row)
}

glm_c <- function(y, X, iXX, pBigMat, verbose = TRUE, threads = 0L) {
    .Call(`_rMVP_glm_c`, y, X, iXX, pBigMat, verbose, threads)
}

mlm_c <- function(y, X, U, vgs, pBigMat, verbose = TRUE, threads = 0L) {
    .Call(`_rMVP_mlm_c`, y, X, U, vgs, pBigMat, verbose, threads)
}

vcf_parser_map <- function(vcf_file, out) {
    .Call(`_rMVP_vcf_parser_map`, vcf_file, out)
}

vcf_parser_genotype <- function(vcf_file, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_rMVP_vcf_parser_genotype`, vcf_file, pBigMat, maxLine, threads, verbose))
}

hapmap_parser_map <- function(hmp_file, out) {
    .Call(`_rMVP_hapmap_parser_map`, hmp_file, out)
}

hapmap_parser_genotype <- function(hmp_file, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_rMVP_hapmap_parser_genotype`, hmp_file, pBigMat, maxLine, threads, verbose))
}

numeric_scan <- function(num_file) {
    .Call(`_rMVP_numeric_scan`, num_file)
}

write_bfile <- function(pBigMat, bed_file, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_rMVP_write_bfile`, pBigMat, bed_file, threads, verbose))
}

read_bfile <- function(bed_file, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_rMVP_read_bfile`, bed_file, pBigMat, maxLine, threads, verbose))
}

fit_diago_brent <- function(Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose) {
    .Call(`_rMVP_fit_diago_brent`, Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose)
}

crossprodcpp <- function(X) {
    .Call(`_rMVP_crossprodcpp`, X)
}

geninv <- function(GG) {
    .Call(`_rMVP_geninv`, GG)
}

impute_marker <- function(pBigMat, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_rMVP_impute_marker`, pBigMat, threads, verbose))
}

hasNA <- function(pBigMat) {
    .Call(`_rMVP_hasNA`, pBigMat)
}

kin_cal <- function(pBigMat, threads = 0L) {
    .Call(`_rMVP_kin_cal`, pBigMat, threads)
}

